### ISSUE TITLE
The system does not work with more than one chip in the scheme.

### ISSUE THREAD

**Issue by EtnasSoft** [Droog71/CD74HC4067#2]
If I place a single CD74HC4067, all the readings are correct. The moment another is added, the values are corrupted. You don't even need to connect the new chip to the MCU.

The problem is easily reproduced even with the examples of the component:
https://wokwi.com/projects/367007283236072449

Simply add a new CD74HC4067 to the scene and the system stops working.

**Comment by skolodi** [comment]
In my Case I test 2 options:

a) With 1 CD74HC4067, doesn't work (No one measure can read). See project here: 
https://wokwi.com/projects/376955374425446401

b) With 4 CD74HC4067 (Non oficial Version) It's works perfect. 64 Measures without problem. See project here:
https://wokwi.com/projects/376936530062516225

**Comment by Droog71** [comment]
Thanks for reporting this bug. It has been fixed.
Here is an example: https://wokwi.com/projects/378345758812972033
