### ISSUE TITLE
Multiplexer (digital) does not work ??

### ISSUE THREAD

**Issue by eltomjan** [Droog71/CD74HC4067#3]
https://github.com/Droog71/CD74HC4067/blob/d77b14b063a2736e3fe098ead026d99c1cbc0653/src/main.c#L124

Would tell there is problem, it should be done in init - you cannot get H on pin while switching I/O mode. At least in simulator there is **Low** still - maybe be kind of PWM (?)

https://github.com/Droog71/CD74HC4067/blob/d77b14b063a2736e3fe098ead026d99c1cbc0653/src/main.c#L114
Did not work untill changed _pin_dac_write_ to `pin_write`

Or what about (de-)multiplexer attribute ?

**Comment by Droog71** [comment]
I'm not sure what you're asking here.
Have you checked the examples from README.md?
Multiplexing with potentiometers -> https://wokwi.com/projects/366560040454111233
Multiplexing with DIP switches -> https://wokwi.com/projects/367007283236072449
Driving LEDs -> https://wokwi.com/projects/366745528502490113
Demultiplexing with analog values -> https://wokwi.com/projects/366644917441189889

**Comment by eltomjan** [comment]
Ok, it is also a bit HW/emulator related...

I know there is even working test, but more important is non-working example:
https://wokwi.com/projects/395576938521384961
There are original and my slightly changed chips in parallel.
If you delete my chip, you will not be able to get H from channel 3 thru original multiplexer.

In case you turn DIP2 to ON state, logical 1 thru channel 3 is multiplexed to COM output and Green LED shows H.
If you switch it off again, both LEDs are still powered - do not know why, but it is also somehow code related.
_For example serial print of H only fixed that, but then changed it to ignore repeated prints and problem again, even 100R resistor did not fixed that._

**Comment by Droog71** [comment]
> Ok, it is also a bit HW/emulator related...
> 
> I know there is even working test, but more important is non-working example: https://wokwi.com/projects/395576938521384961 There are original and my slightly changed chips in parallel. If you delete my chip, you will not be able to get H from channel 3 thru original multiplexer.
> 
> In case you turn DIP2 to ON state, logical 1 thru channel 3 is multiplexed to COM output and Green LED shows H. If you switch it off again, both LEDs are still powered - do not know why, but it is also somehow code related. _For example serial print of H only fixed that, but then changed it to ignore repeated prints and problem again, even 100R resistor did not fixed that._

- You cannot use the TX & RX pins of the Arduino with a device like the CD74HC4067 while also using serial communication. It is better to not use the TX & RX pins for this sort of thing at all.
- The output of the COM pin on the CD74HC4067 is an analog value. Due to the way Wokwi works, you can not get a digital HIGH with digitalRead() from an analog device such as a potentiometer. So, in this project, you will need to use analogRead() with an analog input. With a real Arduino Nano, not in a simulation, you can use digitalRead() with an analog signal and you will get a digital HIGH if the voltage is greater than 3 volts.
- Digital output on the COM pin could be implemented using another attritube if there is demand for it.

**Comment by Droog71** [comment]
Ok, this feature has been implemented.
You can enable it with the attribute "digitalMode".
Here is an example: https://wokwi.com/projects/367007283236072449
Thanks for the suggestion.

**Comment by eltomjan** [comment]
### Sorry, but there is still "HW" bug ??

In `void chip_timer_callback(void *data)` you switch `pin_mode(chip->COM, INPUT_PULLDOWN);` and in `void digital_mode(void *data)` to `pin_mode(chip->COM, OUTPUT);`.

This is non-sense - you cannot use single pin for input and output same time ??
Even simulation does not work similar like possible HW.
While pin is input, there is no value except possible pull down/up, when it is output, there could be some, but in case you are switching it quickly, you get non-sense - part of time output value, rest something "undefined" and definitely different,

So once again - it is quite tricky chip and you cannot simulate it easily, but to get basic functionality, you may decide which way it should work during setup and then do not check again to be able to use COM as output.

Do you understand ?
### There is still no chance to get H on COM as it is OUTPUT H / INPUT_PULLDOWN in a loop.

There was even possible fix in https://wokwi.com/projects/395576938521384961 - have you seen **4067.chip.c** there ?

In case original 4067 is fixed, it must be possible to turn on LED by switching DIP2 to ON without my changed 4067 chip (delete it).

**Comment by Droog71** [comment]
> ### Sorry, but there is still "HW" bug ??
> In `void chip_timer_callback(void *data)` you switch `pin_mode(chip->COM, INPUT_PULLDOWN);` and in `void digital_mode(void *data)` to `pin_mode(chip->COM, OUTPUT);`.
> 
> This is non-sense - you cannot use single pin for input and output same time ?? Even simulation does not work similar like possible HW. While pin is input, there is no value except possible pull down/up, when it is output, there could be some, but in case you are switching it quickly, you get non-sense - part of time output value, rest something "undefined" and definitely different,
> 
> So once again - it is quite tricky chip and you cannot simulate it easily, but to get basic functionality, you may decide which way it should work during setup and then do not check again to be able to use COM as output.
> 
> Do you understand ?
> 
> ### There is still no chance to get H on COM as it is OUTPUT H / INPUT_PULLDOWN in a loop.
> There was even possible fix in https://wokwi.com/projects/395576938521384961 - have you seen **4067.chip.c** there ?
> 
> In case original 4067 is fixed, it must be possible to turn on LED by switching DIP2 to ON without my changed 4067 chip (delete it).

You have some misconceptions about the source code for the custom chip.
Here is a working version of your project: https://wokwi.com/projects/396718463981608961
